fullnameOverride: pg
existingSecret: db-secret
postgresqlDatabase: users


service:
  type: NodePort
  port: 5433

persistence:
  enabled: true
  size: 1Gi

resources:
  requests:
    memory: 256Mi
    cpu: 250m 
    
initdbScripts:
 psql.sql: | 
    create table users (  id serial primary key, first_name varchar(200), last_name varchar(200), email varchar(50));
   create table orders ( id  serial primary key, user_id  integer, price  integer, complete boolean, date timestamp, constraint fk_orders_user foreign key (user_id) REFERENCES users (id)

   );
    insert into users ( id, first_name,last_name ) values (1, 'Ivan','Ivanov', 'ivan@1.ru'),(2, 'Jon', 'First', 'jon@1.ru');